services:
  - type: web
    name: research-api
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY      # Add in Render dashboard (don't commit secrets)
        sync: false
      - key: OPENAI_API_BASE
        value: https://api.openai.com/v1
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: TAVILY_API_KEY      # Optional
        sync: false
